name: news_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  fade_shimmer: ^2.2.0
  flutter:
    sdk: flutter
  
  flutter_bloc: ^8.1.4
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  http: ^1.2.1
  iconsax: ^0.0.8
  persistent_bottom_nav_bar: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
